# Generated by Django 3.2.2 on 2021-07-27 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('espacio', models.IntegerField()),
                ('numero_habitacion', models.IntegerField()),
                ('especificaciones', models.CharField(max_length=60)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Motel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=30)),
                ('telefono', models.IntegerField()),
                ('instagram', models.CharField(max_length=30)),
                ('facebook', models.CharField(max_length=30)),
                ('whatsapp', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('documento', models.IntegerField(unique=True, verbose_name='numero de documento')),
                ('nombre_usuario', models.CharField(max_length=30, unique=True, verbose_name='nombre de usuario')),
                ('nombres', models.CharField(max_length=30, verbose_name='nombres')),
                ('apellidos', models.CharField(max_length=30, verbose_name='apellidos')),
                ('usuario_activo', models.BooleanField(default=True)),
                ('usuario_administrador', models.BooleanField(default=False)),
                ('edad', models.IntegerField(default=18, verbose_name='edad')),
                ('email', models.EmailField(max_length=30, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(max_length=10)),
                ('fecha_reserva', models.DateField()),
                ('id_habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MD_BD.habitacion')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='habitacion',
            name='id_motel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MD_BD.motel'),
        ),
    ]
